// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: visit_log.proto

public final class VisitLog {
    private VisitLog() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface requestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:request)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required string requestId = 1;</code>
         */
        boolean hasRequestId();

        /**
         * <code>required string requestId = 1;</code>
         */
        java.lang.String getRequestId();

        /**
         * <code>required string requestId = 1;</code>
         */
        com.google.protobuf.ByteString
        getRequestIdBytes();

        /**
         * <code>optional .visitTime visitTimeRange = 2;</code>
         */
        boolean hasVisitTimeRange();

        /**
         * <code>optional .visitTime visitTimeRange = 2;</code>
         */
        VisitLog.visitTime getVisitTimeRange();

        /**
         * <code>optional .visitTime visitTimeRange = 2;</code>
         */
        VisitLog.visitTimeOrBuilder getVisitTimeRangeOrBuilder();
    }

    /**
     * Protobuf type {@code request}
     */
    public static final class request extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:request)
            requestOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use request.newBuilder() to construct.
        private request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private request() {
            requestId_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private request(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            requestId_ = bs;
                            break;
                        }
                        case 18: {
                            VisitLog.visitTime.Builder subBuilder = null;
                            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                                subBuilder = visitTimeRange_.toBuilder();
                            }
                            visitTimeRange_ = input.readMessage(VisitLog.visitTime.PARSER, extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(visitTimeRange_);
                                visitTimeRange_ = subBuilder.buildPartial();
                            }
                            bitField0_ |= 0x00000002;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return VisitLog.internal_static_request_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return VisitLog.internal_static_request_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            VisitLog.request.class, VisitLog.request.Builder.class);
        }

        private int bitField0_;
        public static final int REQUESTID_FIELD_NUMBER = 1;
        private volatile java.lang.Object requestId_;

        /**
         * <code>required string requestId = 1;</code>
         */
        public boolean hasRequestId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required string requestId = 1;</code>
         */
        public java.lang.String getRequestId() {
            java.lang.Object ref = requestId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    requestId_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string requestId = 1;</code>
         */
        public com.google.protobuf.ByteString
        getRequestIdBytes() {
            java.lang.Object ref = requestId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                requestId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int VISITTIMERANGE_FIELD_NUMBER = 2;
        private VisitLog.visitTime visitTimeRange_;

        /**
         * <code>optional .visitTime visitTimeRange = 2;</code>
         */
        public boolean hasVisitTimeRange() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional .visitTime visitTimeRange = 2;</code>
         */
        public VisitLog.visitTime getVisitTimeRange() {
            return visitTimeRange_ == null ? VisitLog.visitTime.getDefaultInstance() : visitTimeRange_;
        }

        /**
         * <code>optional .visitTime visitTimeRange = 2;</code>
         */
        public VisitLog.visitTimeOrBuilder getVisitTimeRangeOrBuilder() {
            return visitTimeRange_ == null ? VisitLog.visitTime.getDefaultInstance() : visitTimeRange_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasRequestId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeMessage(2, getVisitTimeRange());
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, getVisitTimeRange());
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof VisitLog.request)) {
                return super.equals(obj);
            }
            VisitLog.request other = (VisitLog.request) obj;

            boolean result = true;
            result = result && (hasRequestId() == other.hasRequestId());
            if (hasRequestId()) {
                result = result && getRequestId()
                        .equals(other.getRequestId());
            }
            result = result && (hasVisitTimeRange() == other.hasVisitTimeRange());
            if (hasVisitTimeRange()) {
                result = result && getVisitTimeRange()
                        .equals(other.getVisitTimeRange());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasRequestId()) {
                hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
                hash = (53 * hash) + getRequestId().hashCode();
            }
            if (hasVisitTimeRange()) {
                hash = (37 * hash) + VISITTIMERANGE_FIELD_NUMBER;
                hash = (53 * hash) + getVisitTimeRange().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static VisitLog.request parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static VisitLog.request parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static VisitLog.request parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static VisitLog.request parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static VisitLog.request parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static VisitLog.request parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static VisitLog.request parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static VisitLog.request parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static VisitLog.request parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static VisitLog.request parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static VisitLog.request parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static VisitLog.request parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(VisitLog.request prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code request}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:request)
                VisitLog.requestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return VisitLog.internal_static_request_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return VisitLog.internal_static_request_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                VisitLog.request.class, VisitLog.request.Builder.class);
            }

            // Construct using VisitLog.request.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getVisitTimeRangeFieldBuilder();
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                requestId_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                if (visitTimeRangeBuilder_ == null) {
                    visitTimeRange_ = null;
                } else {
                    visitTimeRangeBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return VisitLog.internal_static_request_descriptor;
            }

            @java.lang.Override
            public VisitLog.request getDefaultInstanceForType() {
                return VisitLog.request.getDefaultInstance();
            }

            @java.lang.Override
            public VisitLog.request build() {
                VisitLog.request result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public VisitLog.request buildPartial() {
                VisitLog.request result = new VisitLog.request(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.requestId_ = requestId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                if (visitTimeRangeBuilder_ == null) {
                    result.visitTimeRange_ = visitTimeRange_;
                } else {
                    result.visitTimeRange_ = visitTimeRangeBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof VisitLog.request) {
                    return mergeFrom((VisitLog.request) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(VisitLog.request other) {
                if (other == VisitLog.request.getDefaultInstance()) return this;
                if (other.hasRequestId()) {
                    bitField0_ |= 0x00000001;
                    requestId_ = other.requestId_;
                    onChanged();
                }
                if (other.hasVisitTimeRange()) {
                    mergeVisitTimeRange(other.getVisitTimeRange());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasRequestId()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                VisitLog.request parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (VisitLog.request) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private java.lang.Object requestId_ = "";

            /**
             * <code>required string requestId = 1;</code>
             */
            public boolean hasRequestId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required string requestId = 1;</code>
             */
            public java.lang.String getRequestId() {
                java.lang.Object ref = requestId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        requestId_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string requestId = 1;</code>
             */
            public com.google.protobuf.ByteString
            getRequestIdBytes() {
                java.lang.Object ref = requestId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    requestId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string requestId = 1;</code>
             */
            public Builder setRequestId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                requestId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string requestId = 1;</code>
             */
            public Builder clearRequestId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                requestId_ = getDefaultInstance().getRequestId();
                onChanged();
                return this;
            }

            /**
             * <code>required string requestId = 1;</code>
             */
            public Builder setRequestIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                requestId_ = value;
                onChanged();
                return this;
            }

            private VisitLog.visitTime visitTimeRange_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    VisitLog.visitTime, VisitLog.visitTime.Builder, VisitLog.visitTimeOrBuilder> visitTimeRangeBuilder_;

            /**
             * <code>optional .visitTime visitTimeRange = 2;</code>
             */
            public boolean hasVisitTimeRange() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional .visitTime visitTimeRange = 2;</code>
             */
            public VisitLog.visitTime getVisitTimeRange() {
                if (visitTimeRangeBuilder_ == null) {
                    return visitTimeRange_ == null ? VisitLog.visitTime.getDefaultInstance() : visitTimeRange_;
                } else {
                    return visitTimeRangeBuilder_.getMessage();
                }
            }

            /**
             * <code>optional .visitTime visitTimeRange = 2;</code>
             */
            public Builder setVisitTimeRange(VisitLog.visitTime value) {
                if (visitTimeRangeBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    visitTimeRange_ = value;
                    onChanged();
                } else {
                    visitTimeRangeBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000002;
                return this;
            }

            /**
             * <code>optional .visitTime visitTimeRange = 2;</code>
             */
            public Builder setVisitTimeRange(
                    VisitLog.visitTime.Builder builderForValue) {
                if (visitTimeRangeBuilder_ == null) {
                    visitTimeRange_ = builderForValue.build();
                    onChanged();
                } else {
                    visitTimeRangeBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000002;
                return this;
            }

            /**
             * <code>optional .visitTime visitTimeRange = 2;</code>
             */
            public Builder mergeVisitTimeRange(VisitLog.visitTime value) {
                if (visitTimeRangeBuilder_ == null) {
                    if (((bitField0_ & 0x00000002) == 0x00000002) &&
                            visitTimeRange_ != null &&
                            visitTimeRange_ != VisitLog.visitTime.getDefaultInstance()) {
                        visitTimeRange_ =
                                VisitLog.visitTime.newBuilder(visitTimeRange_).mergeFrom(value).buildPartial();
                    } else {
                        visitTimeRange_ = value;
                    }
                    onChanged();
                } else {
                    visitTimeRangeBuilder_.mergeFrom(value);
                }
                bitField0_ |= 0x00000002;
                return this;
            }

            /**
             * <code>optional .visitTime visitTimeRange = 2;</code>
             */
            public Builder clearVisitTimeRange() {
                if (visitTimeRangeBuilder_ == null) {
                    visitTimeRange_ = null;
                    onChanged();
                } else {
                    visitTimeRangeBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            /**
             * <code>optional .visitTime visitTimeRange = 2;</code>
             */
            public VisitLog.visitTime.Builder getVisitTimeRangeBuilder() {
                bitField0_ |= 0x00000002;
                onChanged();
                return getVisitTimeRangeFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .visitTime visitTimeRange = 2;</code>
             */
            public VisitLog.visitTimeOrBuilder getVisitTimeRangeOrBuilder() {
                if (visitTimeRangeBuilder_ != null) {
                    return visitTimeRangeBuilder_.getMessageOrBuilder();
                } else {
                    return visitTimeRange_ == null ?
                            VisitLog.visitTime.getDefaultInstance() : visitTimeRange_;
                }
            }

            /**
             * <code>optional .visitTime visitTimeRange = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    VisitLog.visitTime, VisitLog.visitTime.Builder, VisitLog.visitTimeOrBuilder>
            getVisitTimeRangeFieldBuilder() {
                if (visitTimeRangeBuilder_ == null) {
                    visitTimeRangeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            VisitLog.visitTime, VisitLog.visitTime.Builder, VisitLog.visitTimeOrBuilder>(
                            getVisitTimeRange(),
                            getParentForChildren(),
                            isClean());
                    visitTimeRange_ = null;
                }
                return visitTimeRangeBuilder_;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:request)
        }

        // @@protoc_insertion_point(class_scope:request)
        private static final VisitLog.request DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new VisitLog.request();
        }

        public static VisitLog.request getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<request>
                PARSER = new com.google.protobuf.AbstractParser<request>() {
            @java.lang.Override
            public request parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new request(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<request> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<request> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public VisitLog.request getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface visitTimeOrBuilder extends
            // @@protoc_insertion_point(interface_extends:visitTime)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional int64 startTime = 1;</code>
         */
        boolean hasStartTime();

        /**
         * <code>optional int64 startTime = 1;</code>
         */
        long getStartTime();

        /**
         * <code>optional int64 endTIme = 2;</code>
         */
        boolean hasEndTIme();

        /**
         * <code>optional int64 endTIme = 2;</code>
         */
        long getEndTIme();
    }

    /**
     * Protobuf type {@code visitTime}
     */
    public static final class visitTime extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:visitTime)
            visitTimeOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use visitTime.newBuilder() to construct.
        private visitTime(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private visitTime() {
            startTime_ = 0L;
            endTIme_ = 0L;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private visitTime(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            bitField0_ |= 0x00000001;
                            startTime_ = input.readInt64();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            endTIme_ = input.readInt64();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return VisitLog.internal_static_visitTime_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return VisitLog.internal_static_visitTime_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            VisitLog.visitTime.class, VisitLog.visitTime.Builder.class);
        }

        private int bitField0_;
        public static final int STARTTIME_FIELD_NUMBER = 1;
        private long startTime_;

        /**
         * <code>optional int64 startTime = 1;</code>
         */
        public boolean hasStartTime() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional int64 startTime = 1;</code>
         */
        public long getStartTime() {
            return startTime_;
        }

        public static final int ENDTIME_FIELD_NUMBER = 2;
        private long endTIme_;

        /**
         * <code>optional int64 endTIme = 2;</code>
         */
        public boolean hasEndTIme() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional int64 endTIme = 2;</code>
         */
        public long getEndTIme() {
            return endTIme_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt64(1, startTime_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt64(2, endTIme_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(1, startTime_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(2, endTIme_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof VisitLog.visitTime)) {
                return super.equals(obj);
            }
            VisitLog.visitTime other = (VisitLog.visitTime) obj;

            boolean result = true;
            result = result && (hasStartTime() == other.hasStartTime());
            if (hasStartTime()) {
                result = result && (getStartTime()
                        == other.getStartTime());
            }
            result = result && (hasEndTIme() == other.hasEndTIme());
            if (hasEndTIme()) {
                result = result && (getEndTIme()
                        == other.getEndTIme());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasStartTime()) {
                hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getStartTime());
            }
            if (hasEndTIme()) {
                hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getEndTIme());
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static VisitLog.visitTime parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static VisitLog.visitTime parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static VisitLog.visitTime parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static VisitLog.visitTime parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static VisitLog.visitTime parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static VisitLog.visitTime parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static VisitLog.visitTime parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static VisitLog.visitTime parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static VisitLog.visitTime parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static VisitLog.visitTime parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static VisitLog.visitTime parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static VisitLog.visitTime parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(VisitLog.visitTime prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code visitTime}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:visitTime)
                VisitLog.visitTimeOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return VisitLog.internal_static_visitTime_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return VisitLog.internal_static_visitTime_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                VisitLog.visitTime.class, VisitLog.visitTime.Builder.class);
            }

            // Construct using VisitLog.visitTime.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                startTime_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000001);
                endTIme_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return VisitLog.internal_static_visitTime_descriptor;
            }

            @java.lang.Override
            public VisitLog.visitTime getDefaultInstanceForType() {
                return VisitLog.visitTime.getDefaultInstance();
            }

            @java.lang.Override
            public VisitLog.visitTime build() {
                VisitLog.visitTime result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public VisitLog.visitTime buildPartial() {
                VisitLog.visitTime result = new VisitLog.visitTime(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.startTime_ = startTime_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.endTIme_ = endTIme_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof VisitLog.visitTime) {
                    return mergeFrom((VisitLog.visitTime) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(VisitLog.visitTime other) {
                if (other == VisitLog.visitTime.getDefaultInstance()) return this;
                if (other.hasStartTime()) {
                    setStartTime(other.getStartTime());
                }
                if (other.hasEndTIme()) {
                    setEndTIme(other.getEndTIme());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                VisitLog.visitTime parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (VisitLog.visitTime) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private long startTime_;

            /**
             * <code>optional int64 startTime = 1;</code>
             */
            public boolean hasStartTime() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional int64 startTime = 1;</code>
             */
            public long getStartTime() {
                return startTime_;
            }

            /**
             * <code>optional int64 startTime = 1;</code>
             */
            public Builder setStartTime(long value) {
                bitField0_ |= 0x00000001;
                startTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 startTime = 1;</code>
             */
            public Builder clearStartTime() {
                bitField0_ = (bitField0_ & ~0x00000001);
                startTime_ = 0L;
                onChanged();
                return this;
            }

            private long endTIme_;

            /**
             * <code>optional int64 endTIme = 2;</code>
             */
            public boolean hasEndTIme() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional int64 endTIme = 2;</code>
             */
            public long getEndTIme() {
                return endTIme_;
            }

            /**
             * <code>optional int64 endTIme = 2;</code>
             */
            public Builder setEndTIme(long value) {
                bitField0_ |= 0x00000002;
                endTIme_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 endTIme = 2;</code>
             */
            public Builder clearEndTIme() {
                bitField0_ = (bitField0_ & ~0x00000002);
                endTIme_ = 0L;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:visitTime)
        }

        // @@protoc_insertion_point(class_scope:visitTime)
        private static final VisitLog.visitTime DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new VisitLog.visitTime();
        }

        public static VisitLog.visitTime getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<visitTime>
                PARSER = new com.google.protobuf.AbstractParser<visitTime>() {
            @java.lang.Override
            public visitTime parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new visitTime(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<visitTime> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<visitTime> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public VisitLog.visitTime getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_request_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_request_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_visitTime_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_visitTime_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\017visit_log.proto\"@\n\007request\022\021\n\trequestI" +
                        "d\030\001 \002(\t\022\"\n\016visitTimeRange\030\002 \001(\0132\n.visitT" +
                        "ime\"/\n\tvisitTime\022\021\n\tstartTime\030\001 \001(\003\022\017\n\007e" +
                        "ndTIme\030\002 \001(\003B\nB\010VisitLog"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_request_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_request_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_request_descriptor,
                new java.lang.String[]{"RequestId", "VisitTimeRange",});
        internal_static_visitTime_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_visitTime_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_visitTime_descriptor,
                new java.lang.String[]{"StartTime", "EndTIme",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
